import { StyleSheet } from 'react-native';
import * as Colors from 'presentation/styles/colors';

export default StyleSheet.create({
  mapZoomOut: {
    marginBottom: 100,
  },
  smallDot: {
    marginTop: 2,
    height: 3,
    width: 3,
    borderRadius: 25,
    backgroundColor: Colors.titleGrey,
    alignSelf: 'center',
  },
  bigDotFrom: {
    marginBottom: -1,
    height: 10,
    width: 10,
    borderWidth: 2,
    borderColor: Colors.fromGreen,
    borderRadius: 45,
  },
  bigDotTo: {
    height: 10,
    width: 10,
    borderWidth: 2,
    borderColor: Colors.toBlue,
    borderRadius: 45,
    marginTop: 2,
  },
  shadow: {
    height: 25,
    borderTopLeftRadius: 25,
    borderTopRightRadius: 25,
    marginBottom: -22.5,
    marginLeft: -1,
    marginRight: -1,
    overflow: 'hidden',
  },
  interactableContainer: {
    position: 'absolute',
    height: '100%',
    width: '100%',
    borderColor: Colors.lightGrey,
    borderWidth: 0.3,
  },
  interactableBottomPad: {
    backgroundColor: Colors.white,
  },
  touchableContainer: {
    width: '100%',
  },
  middleContentWrap: {
    backgroundColor: Colors.white,
  },
  textTitle: {
    color: '#9FB1C2',
    fontSize: 10,
    lineHeight: 10,
    marginBottom: 3,
  },
  textTitleValue: {
    color: '#0D0D0D',
    fontWeight: '500',
    fontSize: 16,
    lineHeight: 16,
  },
  transportInfoContainer: {
    backgroundColor: Colors.white,
    borderTopRightRadius: 25,
    borderTopLeftRadius: 25,
    alignItems: 'center',
  },
  directionIcon: {
    width: 0,
    height: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 5,
    borderRightWidth: 5,
    borderBottomWidth: 6,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: '#3D4763',
  },
  transportNumber: {
    marginLeft: 10,
    marginRight: 15,
    fontSize: 18,
    fontWeight: 'bold',
  },
  gpsIconSize: {
    height: 20,
    width: 42,
  },
  gpsContainer: {
    backgroundColor: Colors.fromGreen,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
  },
  whiteColor: {
    color: Colors.white,
  },
  addressContainer: {
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 0,
  },
  eyeIconContainer: {
    marginRight: 21,
  },
  transportIcon: {
    height: 30,
    width: 30,
    margin: 20,
  },
  transportArrowWrapper: {
    alignItems: 'center',
    height: 40,
    width: 40,
    margin: 15,
  },
  transportBortNumber: {
    position: 'absolute',
    top: 0,
    width: 70,
    textAlign: 'center',
  },
  routeTabItemForward: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    height: 32,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    borderWidth: 1,
    borderColor: '#ABBFD6',
  },
  routeTabItemBackward: {
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    height: 32,
    borderTopRightRadius: 5,
    borderBottomRightRadius: 5,
    borderWidth: 1,
    borderColor: '#ABBFD6',
  },
  backButton: {
    position: 'absolute',
    top: 55,
    paddingTop: 20,
    paddingHorizontal: 20,
    paddingBottom: 20,
  },
  flex1: {
    flex: 1,
  },
  marginTop20: {
    marginTop: 20,
  },
  marginLeft5: {
    marginLeft: 5,
  },
  marginTop8: {
    marginTop: 8,
  },
  paddingHorizontal20: {
    paddingHorizontal: 20,
  },
  marginTop10: {
    marginTop: 10,
  },
  marginRight30: {
    marginRight: 30,
  },
  marginRight20: {
    marginRight: 20,
  },
  buttonsRow: {
    marginTop: 20,
    marginBottom: 2,
  },
  flatList: {
    backgroundColor: Colors.white,
    position: 'relative',
    bottom: 0,
    width: '100%',
  },
  flatListItem: {
    height: 50,
    flex: 1,
  },
  divider: {
    marginLeft: 11,
  },
  firstItemLineWrap: {
    marginRight: 11,
  },
  firstItemDot: {
    backgroundColor: '#ABBFD6',
    width: 15,
    height: 15,
    borderRadius: 7.5,
    marginTop: 16,
    marginLeft: 2.5,
  },
  firstItemLine: {
    backgroundColor: '#061040',
    width: 1,
    height: 18,
    marginLeft: 10,
    marginTop: 2,
  },
  lastItemLineWrap: {
    marginRight: 11,
    justifyContent: 'center',
  },
  lastItemLine: {
    backgroundColor: '#061040',
    width: 1,
    height: 18,
    marginLeft: 10,
    marginBottom: 2,
  },
  lastItemDot: {
    backgroundColor: '#061040',
    width: 15,
    height: 15,
    borderRadius: 7.5,
    marginBottom: 16,
    marginLeft: 2.5,
  },
  normalItemLineWrap: {
    marginRight: 15,
  },
  normalItemLineTop: {
    backgroundColor: '#061040',
    width: 1,
    height: 21,
    marginLeft: 10,
  },
  normalItemLineDot: {
    width: 9,
    height: 9,
    borderRadius: 4.5,
    borderColor: '#061040',
    borderWidth: 1,
    marginLeft: 6,
  },
  normalItemLineBottom: {
    backgroundColor: '#061040',
    width: 1,
    height: 22,
    marginLeft: 10,
  },
  rightArrowWrap: {
    justifyContent: 'center',
  },
  warningButton: {
    right: 20,
    position: 'absolute',
  },
  warningMessageContainer: {
    left: 20,
    right: 20,
    backgroundColor: Colors.white,
    position: 'absolute',
    minHeight: 99,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.22,
    shadowRadius: 2.22,
    elevation: 3,
  },
  warningMessage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 10,
  },
  warningIcon: {
    width: 49,
    backgroundColor: 'rgba(254,205,0,0.15)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  warningCloseIcon: {
    paddingTop: 10,
    paddingRight: 10,
  },
  loaderContainer: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  loader: {
    height: 200,
  },
  tipsTriangle: {
    height: 0,
    width: 0,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderRightWidth: 15,
    borderBottomWidth: 15,
    transform: [{ rotate: '180deg' }],
    borderLeftWidth: 15,
    borderRightColor: 'transparent',
    borderLeftColor: 'transparent',
    borderBottomColor: 'rgba(228,37,72,0.85)',
    marginBottom: 93,
  },
  tipsContainer: {
    backgroundColor: 'rgba(228,37,72,0.9)',
    height: '8%',
    width: '102%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
    borderRadius: 7,
  },
});
