export const FAVORITE_STOPS_KEY = 'FAVORITE_STOPS_KEY_ICITY';

export const FAVORITE_ROUTES_KEY = 'FAVORITE_ROUTES_KEY_ICITY';

export const SUBSCRIBED_ROUTES_KEY = 'SUBSCRIBED_ROUTES_KEY_ICITY';

export const API_CALL_INTERVAL = 15000;

export const JOB_NAME_PREFIX = 'job_';

export const ROUTE_VERSION_KEY = 'ROUTE_VERSION_KEY_ICITY';

export const ALL_ROUTES_KEY = 'ALL_ROUTES_KEY_ICITY';

export const DATE_FORMAT_KEY = 'DATE_FORMAT_KEY_ICITY';

export const IS_VISIBLE_SUBURBAN_FILTER_KEY = 'IS_VISIBLE_SUBURBAN_FILTER';
